tl-its-umich-edu/canvas-course-manager-next

ccm_web/client/src/App.tsx
ccm_web/client/src/components/FeatureCard.tsx
ccm_web/client/src/components/Home.tsx
ccm_web/client/src/pages/Home.tsx
ccm_web/package-lock.json
ccm_web/package.json

Added Material UI dependency.
Created a skeleton for a landing page.
No theme created, no navigation added.   Just something for people to check out if its a reasonable starting point.

First pass at integrating Material  UI

---

ccm_web/client/src/App.tsx
ccm_web/client/src/models/FeatureUIData.tsx
ccm_web/client/src/models/feature.ts
ccm_web/client/src/pages/Home.tsx

Changes for category based home page

---

ccm_web/server/localTypes/ltijs/index.d.ts

It looks like I missed a few things that the linter is now complaining about in `server/localTypes/ltijs`. They should be addressed here. The PR will resolve #71.

Fix a few misc. `ltijs` typing issues (#71)

---

README.md

I don't like ambiguity or hunting around for documentation.  Let's keep this documentation up to date.
This documentation is as complete as possible with regards to installing the application for development purposes.  It is not exhaustive.  It will need future updates as the project progresses.

README: add steps for configuring dev. environment

---

ccm_web/server/src/user/user.model.ts

Add `user` tableName to decorator (#93)

---

ccm_web/client/src/components/GradebookCanvasValidators.ts
ccm_web/client/src/components/GradebookUploadConfirmationTable.tsx
ccm_web/client/src/pages/GradebookCanvas.tsx

Closes #86 
Created some sample data files
[Canvas Gradebook.zip](https://github.com/tl-its-umich-edu/canvas-course-manager-next/files/6600550/Canvas.Gradebook.zip)

Use override grade when present

---

ccm_web/client/src/pages/BulkSectionCreate.tsx
ccm_web/client/src/pages/GradebookCanvas.tsx

Fixes #77 
Note:  This help link will be made functional in another issue

Text content changes

---

ccm_web/client/src/models/models.ts
ccm_web/server/localTypes/express-session/index.d.ts
ccm_web/server/src/api/api.controller.ts
ccm_web/server/src/api/api.interfaces.ts
ccm_web/server/src/api/api.service.ts
ccm_web/server/src/lti/lti.service.ts
config/lti_dev_key_sample.json

Fixes #106 
This PR builds upon on the work done by @ssciolla for integrating Express session library #22. I am pulling certain information from Launch that is will be useful for hold during a user session. I am also sending some information to Frontend as well. I am fulfilling the data needs at this point of time. If there are more we could easily aded

#106 Have some basic launch data available to UI

---

ccm_web/client/src/App.tsx
ccm_web/client/src/hooks/useGlobals.ts
ccm_web/client/src/models/FeatureUIData.tsx
ccm_web/client/src/models/feature.ts
ccm_web/client/src/models/models.ts
ccm_web/client/src/pages/Home.tsx

Fixes #120 
Feature to Role mapping defined in `feature.ts`
Role name to canvas name mapped in `models.ts`
I haven't yet tested how useGlobals' `isAuthenticated` and `error` would work if there were issues.

120 UI feature role accessibility

---

ccm_web/server/src/canvas/canvas.controller.ts
ccm_web/server/src/canvas/canvas.interfaces.ts
ccm_web/server/src/canvas/canvas.utils.ts

#129 error message when needed scopes not selected

---

ccm_web/client/src/models/models.ts
ccm_web/client/src/utils/handleErrors.ts
ccm_web/server/src/api/api.interfaces.ts
ccm_web/server/src/api/api.service.ts
ccm_web/server/src/api/api.utils.ts
ccm_web/server/src/canvas/canvas.service.ts

#156 Refactoring the error handler for canvas  request/responses

---

ccm_web/client/src/pages/GradebookCanvas.tsx

Fixes #74 
Adding the link to the view when you error is caught when upload the no grading schema applied [sample csv](https://drive.google.com/drive/folders/11VARkGgQUpxrDZ3yIiY6zeivJlPrQG-j)

#74 adding the missing course setting link

---

ccm_web/client/src/components/BulkSectionCreateValidators.ts
ccm_web/client/src/pages/BulkSectionCreate.tsx
ccm_web/client/src/utils/canvasSectionNameValidator.ts

Validator(s) for section name too long

---

ccm_web/client/src/models/feature.ts
ccm_web/client/src/models/models.ts

#185 SC should see all the features

---

ccm_web/server/src/canvas/canvas.controller.ts
ccm_web/server/src/canvas/canvas.interfaces.ts

Handle when user hits Cancel on OAuth prompt (#187)

---

ccm_web/server/src/api/api.controller.ts
ccm_web/server/src/api/dtos/api.get.sections.admin.dto.ts

Add additional validation to `GET` `admin/sections` route

---

ccm_web/server/src/canvas/canvas.service.ts

use got default retry statusCodes (iss. #194)

---

ccm_web/server/src/auth/auth.service.ts
ccm_web/server/src/canvas/canvas.model.ts
ccm_web/server/src/user/user.model.ts

Making Database autogenerated Id mandatory in Type definition

---

ccm_web/client/src/App.tsx

I missed removing this unwanted import when merging #224.

Fixing the Type error with Unwanted import

---

ccm_web/client/src/pages/GradebookCanvas.tsx

Add success step to `GradebookCanvas.tsx` (#231)

---

ccm_web/client/src/pages/Home.tsx

Message change after success course rename

---

ccm_web/client/src/components/ConfirmDialog.tsx

Rewire `ConfirmDialog` button to prevent double-focusing (#256)

---

ccm_web/package-lock.json
ccm_web/package.json

Fixes #283 
1. Tested both the Prod and local docker compose
2. Migration ran fine, with the existing and new DB setup
3. Ran the migration up/down command seem to work with the existing setup.

#283 Upgrading to Umzug v3

---

ccm_web/client/src/components/CustomTable.tsx
ccm_web/client/src/components/ValidationErrorTable.tsx

Remove `colSpan` from `TablePagination` usages (#302)

---

ccm_web/server/src/api/api.controller.ts
ccm_web/server/src/api/invalid.token.interceptor.ts
ccm_web/server/src/canvas/invalid.token.interceptor.ts

Only intercept token-related `401` errors (#305)

---

ccm_web/client/src/components/AuthorizePrompt.tsx

#297 word change for pre-auth page

---

ccm_web/server/src/lti/lti.service.ts

The PR aims to resolve #307.
Notes:
I'm requesting reviews from the entire development team, as this is a minuscule code change and others may have expertise regarding LTI and web security to contribute. See issue for details.

Disable `cors` in `LTIService` (#307)

---

ccm_web/client/src/components/FeatureCard.tsx

Streamline tab order on Home page, add hover/ripple for feature cards (#318)

---

ccm_web/server/src/app.module.ts
ccm_web/server/src/main.ts
ccm_web/server/src/no.cache.interceptor.ts

Fixes #320 
This PR is built on the dev-ccm instance. If you like to check it out here https://canvas-test.it.umich.edu/courses/403334/external_tools/43025

#320 Disallow client to store api response

---

ccm_web/client/src/components/CreateSectionWidget.tsx

#322 showing snackbar msg section created

---

ccm_web/client/src/components/Accordion.tsx

Fixes #328 
https://user-images.githubusercontent.com/8579775/152561753-da0f6c3a-7377-4b7b-99f8-91aa81e7d9f1.mov

#328 change the contrast color ratio tabbing accordion

---

ccm_web/client/src/components/MethodSelect.tsx
ccm_web/client/src/components/MultipleUserEnrollmentWorkflow.tsx
ccm_web/client/src/components/RoleSelect.tsx
ccm_web/client/src/components/UserEnrollmentForm.tsx

#324 non-umich text changes

---

ccm_web/client/src/components/BulkEnrollExternalUserConfirmationTable.tsx
ccm_web/client/src/components/BulkEnrollUMUserConfirmationTable.tsx
ccm_web/client/src/components/BulkEnrollUMUserToSectionsConfirmationTable.tsx
ccm_web/client/src/components/BulkSectionCreateUploadConfirmationTable.tsx
ccm_web/client/src/components/CanvasAPIErrorsTable.tsx
ccm_web/client/src/components/CustomTable.tsx
ccm_web/client/src/components/GradebookUploadConfirmationTable.tsx
ccm_web/client/src/components/MultipleSectionEnrollmentWorkflow.tsx
ccm_web/client/src/components/TableCaption.tsx
ccm_web/client/src/components/ThirdPartyGradebookConfirmationTable.tsx
ccm_web/client/src/components/ValidationErrorTable.tsx

The PR aims to resolve #257.
(I only did minimal testing, but I will do some more. This should do the trick.)

Add table captions (#257)

---

ccm_web/client/src/components/Accordion.tsx

Fixes #328 
1. I have the fix in the ccm dev instance so that Janel can review if this is what she is expecting with the fix. She concur it.
2. This PR has been quite a learning in terms of Custom Material UI stuff, how you can grab hold of global css class.

I328 accordion tab change

---

ccm_web/client/src/App.tsx
ccm_web/client/src/components/Breadcrumbs.tsx
ccm_web/client/src/components/Layout.tsx
ccm_web/client/src/components/UserEnrollmentForm.tsx
ccm_web/client/src/pages/AccessDenied.tsx
ccm_web/client/src/pages/AddNonUMUsers.tsx
ccm_web/client/src/pages/AddUMUsers.tsx
ccm_web/client/src/pages/BulkSectionCreate.tsx
ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
ccm_web/client/src/pages/GradebookCanvas.tsx
ccm_web/client/src/pages/Home.tsx
ccm_web/client/src/pages/MergeSections.tsx
ccm_web/client/src/pages/NotFound.tsx

The PR aims to resolve #347, #352, and #353.

Create `Layout` component capturing base styling, breadcrumbs, footer, and development tools (#347, #352, #353)

---

config/.env.sample

Add suggested `FRAME_DOMAIN` value for development to `.env.sample`

---

ccm_web/client/src/components/MultipleSectionEnrollmentWorkflow.tsx
ccm_web/client/src/components/SingleSectionEnrollmentWorkflow.tsx
ccm_web/client/src/models/canvas.ts

#354,346 expand assistant privileges and csv download improvements

---

ccm_web/client/src/api.ts
ccm_web/client/src/components/MultipleSectionEnrollmentWorkflow.tsx
ccm_web/client/src/components/SingleSectionEnrollmentWorkflow.tsx
ccm_web/client/src/components/UserEnrollmentForm.tsx
ccm_web/client/src/models/canvas.ts
ccm_web/server/src/api/api.section.handler.ts
ccm_web/server/src/api/api.service.ts
ccm_web/server/src/api/dtos/api.section.enrollment.dto.ts
ccm_web/server/src/api/dtos/api.section.users.dto.ts
ccm_web/server/src/canvas/canvas.interfaces.ts

Fixes #357 
All the code in the client side that was converting the role with enrollment string is now in handled in Backend.

#357 adjust the role in error report as in csv

---

ccm_web/package-lock.json
ccm_web/package.json
ccm_web/server/src/app.module.ts
ccm_web/server/src/health/health.controller.ts
ccm_web/server/src/health/health.module.ts

This PR aims to resolve #343.
Resource(s):
- https://docs.nestjs.com/recipes/terminus#healthchecks-terminus
- https://github.com/nestjs/terminus

Add root route and database health checks using `@nestjs/terminus` (#343)

---

ccm_web/client/src/components/HelpContact.tsx
ccm_web/client/src/index.tsx
ccm_web/client/src/pages/AccessDenied.tsx
ccm_web/client/src/pages/LaunchError.tsx
ccm_web/server/src/lti/lti.service.ts

The PR aims to resolve #312.
Screenshot of error page

Handle LTI launch error due to browser cookie settings (#312)

---

ccm_web/server/src/api/api.controller.ts
ccm_web/server/src/api/dtos/api.get.sections.admin.dto.ts
ccm_web/server/src/api/dtos/api.get.sections.instructor.dto.ts
ccm_web/server/src/canvas/canvas.controller.ts
ccm_web/server/src/canvas/canvas.interfaces.ts
ccm_web/server/src/canvas/dtos/canvas.oauth.query.dto.ts

This PR adopts DTOS in two new places (queries) to ensure `ValidationPipe` settings are in place.

Use more DTOs

---

ccm_web/client/src/components/UserEnrollmentForm.tsx
ccm_web/client/src/pages/Home.tsx
ccm_web/client/src/utils/validation.ts

Use an imperative validation message with inputs when the field is blank (#372)

---

ccm_web/client/src/components/SectionSelectorWidget.tsx
ccm_web/client/src/models/feature.ts
ccm_web/client/src/pages/MergeSections.tsx

Make UI style and text modifications (#382)

---

docs/add-non-um-users.html
docs/add-um-users.html
docs/create-sections.html
docs/gradebook-canvas.html
docs/gradebook-thirdparty.html
docs/index.html
docs/merge-sections.html

Fixes #79 and #110 
Preview of the documentation
https://pushyamig.github.io/canvas-course-manager-next/

I79 help documentation

---

ccm_web/client/src/api.ts
ccm_web/client/src/components/UserEnrollmentForm.tsx
ccm_web/client/src/models/canvas.ts
ccm_web/server/src/api/api.controller.ts
ccm_web/server/src/api/api.service.ts
ccm_web/server/src/canvas/canvas.interfaces.ts

Resolves #387 
Added the interface, CanvasUserCondensed, which contains name and loginId 
Returns this interface at userExists functions.

fix an issue #387(Add Non-UM User: include found user's name on the screen)

---

ccm_web/.dockerignore

Fix `.dockerignore` pattern (#392)

---

docker-compose-prod.yml
docker-compose.yml

fixes #388 
Testing process:
1. Able to launch the Application both in the Development and Prod mode
2. Able to connect to Dbeaver with MySQL driver.

#388 Upgrading to MySQL8

---

ccm_web/server/src/canvas/canvas.service.ts

This PR finishes resolving #397.

Remove unused import after #398 (#397)

---

docs/index.html

Fixed the minor text change is available at https://pushyamig.github.io/canvas-course-manager-next/
Here is the Prod change https://tl-its-umich-edu.github.io/canvas-course-manager-next/

Minor text change

---

ccm_web/client/src/components/Layout.tsx

Dynamically changing the year for footer

---

ccm_web/client/src/components/MultipleUserEnrollmentWorkflow.tsx
ccm_web/client/src/pages/LaunchError.tsx

Fixes #457 #441 
Test Plan 
#457 : To reproduce the error launch CCM from Safari
#441 : Open Add Non UM user in the Bulk option and see the link is added on the upload CSV page

#457 3rd party cookie alert txt change

---

.vscode/launch.json
README.md
backend/debugpy.py
backend/settings.py
backend/tests/test_setup.py
config/.env.sample
docker-compose.yml

Debug for Django tests
