ccm_web/client/src/App.tsx
ccm_web/client/src/components/FeatureCard.tsx
ccm_web/client/src/models/FeatureCardData.tsx
ccm_web/client/src/models/FeatureUIData.tsx
ccm_web/client/src/models/feature.ts
ccm_web/client/src/pages/Home.tsx

Added basic breadcrumbs.
Automatically constructed from the route so this *should* continue to work when we get more than 2 deep.
Each route is now automatically added as defined by the featureCardProps array defined in Home.tsx (for now)
All features currently direct to the placeholder Merge component (because they have to have a component defined) but use appropriate routes.

Basic breadcrumb implementation.

---

ccm_web/client/src/App.tsx
ccm_web/client/src/components/InlineTextEdit.tsx
ccm_web/client/src/pages/Home.tsx
ccm_web/package-lock.json
ccm_web/package.json

I've done some work to create an inline text field editor for course rename.
I'm not sure how the data is going to get fed into it, and how it is going to save so it's going to have to be modified, but hopefully the general idea is sound.  Right now it is just passed a string, the course name, and a function to pass a string to to save changes.
That function is defined in Home.tsx where the InlineTextEdit element is declared.  I'm sure this will annoy @ssciolla :)
You can enable edit mode by clicking on the pencil icon, or clicking on the disabled text field (I haven't figured out how to override the cursor on the text field thus far)
Click save or cancel to save or cancel.  Enter or num-pad enter save. Escape cancels.  Only changes will be saved.
Trying to save 'reject' as a course name …

Course Rename

---

ccm_web/package-lock.json
ccm_web/package.json
ccm_web/server/app.ts
ccm_web/server/appHandler.ts
ccm_web/server/config.ts
ccm_web/server/logger.ts
config/.env.sample

This PR adds a server logging approach similar to our other applications using the `winston` library, which seems widely used (though has a lot of open PRs/issues). On a high level, a `baseLogger` is set with most configuration; configuration validation logic uses the default logging; the minimum log level shown is set in `app.ts` after the configuration is loaded; and each module sets up a child logger, passing `__filename` so the logger format function can determine the module. The PR aims to resolve #38.
Note: I am choosing to wait on determining the best HTTP request logging approach until we decide whether we will add an additional framework/tool for building out the internal application API. I will separate that piece out into a new issue.
Resources:
* …

Add server logging approach using `winston` (#38)

---

README.md
ccm_web/client/src/App.tsx
ccm_web/package-lock.json
ccm_web/package.json
ccm_web/server/src/api/api.controller.ts
ccm_web/server/src/main.ts

This PR adds an OpenAPI API specification generator and a Swagger UI interface to the project, following the patterns laid out [here](https://docs.nestjs.com/openapi/introduction). Currently, it is only supported in an LTI context (same as the application). The code is only invoked in development. The PR resolves #82.
Note(s): 
* I looked into loading the necessary modules conditionally (so they can only be `devDependencies`), but because decorators are/will be used throughout to generate the spec, this seemed difficult. See https://github.com/nestjs/swagger/issues/184

Add OpenAPI/Swagger (#82)

---

README.md
config/.env.sample

This PR makes two small modifications to fix an incorrect URL in the step-by-step instructions (`/canvas/redirectFromOAuth` => `/canvas/returnFromOAuth`; is already correct under Configuration - Canvas section) and supply a recommended value for `CANVAS_INSTANCE_URL` in `.env.sample` (currently the Canvas test instance, which is consistent with the `LTI_PLATFORM_URL` value provided).

Fix `returnFromOAuth` URL in README, provide recommended `CANVAS_INSTANCE_URL`

---

README.md
config/.env.sample
config/lti_dev_key_sample.json

Resolves #118.
* Changed order of `.env` file steps.  Move creation of file to just before changes need to be made.  There's no reference to the file before then, so it makes sense to put the creation and edit steps together.
* Add explanations to some of the steps.
* Refer to "hostname" instead of "URL" where appropriate.
* Correct hostname in URL for adding tool to course.
* Formatting corrections.
* Removed old step for optionally starting DB independently to avoid race condition.
* Corrected item numbering.
* Update comments for `DOMAIN`
* Correct hostname for `CANVAS_INSTANCE_URL`
* Change `ccm_app_url` references to `ccm_app_hostname`]

documentation and config sample update (iss. #118)

---

README.md
ccm_web/server/src/app.module.ts

As was discussed in an earlier meeting, configured Sequelize to use the winston logger at `debug` level for logging its messages.
CCM's logging level is controlled by the `LOG_LEVEL` directive in `.env`.  If it is not set, the default level is `debug`.  If `LOG_LEVEL` is set to any level higher than `debug` (i.e., `info`, `notice`, `warning`, `error`, etc.), Sequelize's messages will not appear in the output.  (See: https://github.com/winstonjs/winston#logging-levels)
Resolves #91.
This took me longer than expected to implement due to Docker poor performance on my computer.  Having to restart the Docker daemon periodically impacts productivity.

configure Sequelize to log at `debug` level (iss. #91)

---

ccm_web/server/src/app.module.ts
ccm_web/server/src/canvas/canvas.model.ts
ccm_web/server/src/migrations/2021.06.16T19.36.19.create-user.ts
ccm_web/server/src/migrations/2021.06.16T19.36.43.create-canvas-token.ts
ccm_web/server/src/migrator.ts
ccm_web/server/src/user/user.model.ts

This PR modifies existing migrations and model definitions so table name and field names use `snake_case`, with the goal of avoiding case-related issues. Modifying migrations was deemed safe by the team, because we have no deployments; timestamps have been updated. Model and attribute names in TS-code still use `[cC]amelCase`, to be consistent with JS best practices. The PR aims to resolve #126.
**Note: you will need to delete your database volume (`.mysql_data`) before running this locally, and if/when it is merged.**

Switch to using underscored table and field names (#126)

---

ccm_web/server/src/canvas/canvas.service.ts
ccm_web/server/src/user/user.model.ts

This PR fixes the type for `canvasToken` in `user.model.ts` so that it uses the correct `null` value for when it doesn't exist (previously `undefined`). I also simplified some code in `CanvasService.findToken` to return the token (`null` or not) directly. See the issue for more info on the bug. The PR aims to resolve #149.

Correct `User.canvasToken` type to be `CanvasToken | null` (#149)

---

ccm_web/server/src/api/api.controller.ts
ccm_web/server/src/api/api.create.section.handler.ts
ccm_web/server/src/api/api.interfaces.ts
ccm_web/server/src/api/api.service.ts
ccm_web/server/src/api/dtos/api.create.sections.dto.ts
ccm_web/server/src/canvas/canvas.interfaces.ts
ccm_web/server/src/canvas/canvas.scopes.ts
ccm_web/server/src/canvas/canvas.service.ts

Fixes #152 as part Epic #17
This PR is creating an endpoint for creating sections. This Endpoint should be able to handle single section and Multiple sections. The Endpoint creates multiple sections concurrently
**Add the new Scope in the API Developer Key** `url:POST|/api/v1/courses/:course_id/sections`
For creating 60 section it takes about ~2 sec and with retry as well about ~5 sec. I did not see any rating limiting error while working on the issue. So for the max section we could create (60) with CCM shouldn't hit the rate limiting phenomenon.
I have used Promise.all() approach for triggering concurrent creation of sections.
Some of the articles that I explored
coreycleary.me/awaiting-multiple-requests-to-finish-using-promise-all
davidroyer.me/blog/optimized-async-await …

#152, #88 Create sections backend endpoint

---

README.md
ccm_web/.eslintrc.js
ccm_web/Dockerfile
ccm_web/Dockerfile.openshift
ccm_web/ecosystem.config.js
ccm_web/server/src/app.module.ts
ccm_web/server/src/config.ts
ccm_web/server/src/init.ts
ccm_web/server/src/main.ts
ccm_web/server/src/migrator.ts
ccm_web/start.sh
config/.env.sample
docker-compose-prod.yml
docker-compose.yml

This PR prepares the project for OpenShift deployments by doing the following:
- Implementing the `pm2` process manager (in `cluster` mode) for production builds so we can utilize all cores in OpenShift pods, improving performance and resiliency in case of errors
- Creating an `init` script that starts and stops the NestJS application to ensure the configuration is valid and the `ltijs` database tables are initialized before the application is clustered (might be a better way to do this, still thinking about it)
- Working around an issue in OpenShift 3 for deployments by pulling from `node:14-slim` in `build` `Dockerfile` stage (instead of from the `base` stage)
- Working around Docker rate limits by creating an alternate `Dockerfile.openshift` (hopefully we can remove this when we …

Get ready for OpenShift deployment (#42, #175)

---

ccm_web/client/src/components/BulkSectionCreateValidators.ts
ccm_web/client/src/pages/AddUMUsers.tsx
ccm_web/client/src/pages/BulkSectionCreate.tsx

Fixes #160
Add a new empty section validator for bulk section creation
Also fixes an issue where blank lines were being ignored.. functionally ok but messed with line numbers in error messages.  This was present in bulk section create an
[IncludesABlank.csv](https://github.com/tl-its-umich-edu/canvas-course-manager-next/files/7093243/IncludesABlank.csv)
d bulk add UM users.

Bulk Section Create empty line validator

---

ccm_web/client/src/App.tsx
ccm_web/client/src/components/AuthorizePrompt.tsx
ccm_web/client/src/components/Breadcrumbs.tsx
ccm_web/client/src/utils/redirect.ts

This PR changes the OAuth redirect logic so that it shows the user an intermediary prompt with information about the missing integration and a button that when clicked takes them to the Canvas authorize page. The changes include an extraction of the `Breadcrumbs` implementation so that it could be more easily reused (as in the `AuthorizePrompt` block), styling specific to that component would be isolated, and the `App.tsx` component would be streamlined. Language used has been requested and cleared by Janel, but may be adjusted at a later date. The PR aims to resolve #189.

Add `AuthorizePrompt` component, extract `Breadcrumbs` (#189)

---

ccm_web/server/src/api/api.course.handler.ts
ccm_web/server/src/api/api.section.handler.ts
ccm_web/server/src/canvas/canvas.interfaces.ts

This PR follows up on the work of #199, adding the `nonxlist_course_id` field to `CanvasCourseSectionBase` so that the FE can determine whether a course can be unmerged (de-crosslisted) or not (if it's `null`, it's currently part of its original course and can't be unmerged).

Add `nonxlist_course_id` to `CanvasCourseSectionBase`

---

ccm_web/server/src/canvas/canvas.service.ts

Reverts tl-its-umich-edu/canvas-course-manager-next#202
While working on #190 with this change in place, I'm starting to doubt this actually works.  It seemed like it had been working, which is why I thought I'd open it as a standalone PR so others could benefit from it.  However, it seems to not be correct.
I am reverting this change so it doesn't impact anyone else's work.  I'll work on this in the PR for #190 instead.

Revert "use got default retry statusCodes (iss. #194)"

---

ccm_web/server/src/canvas/canvas.service.ts

Reverts tl-its-umich-edu/canvas-course-manager-next#211
That is, it reverts the revert, redoing the original PR.  What I thought was broken actually works.  I wasn't getting the results I expected because of other factors.
**_Now_** I feel silly for having a knee-jerk reaction and reverting my PR, then having to redo it again later. 😨

Redo "use got default retry statusCodes (iss. #194)"

---

ccm_web/client/src/api.ts
ccm_web/client/src/components/Alert.tsx
ccm_web/client/src/components/ConfirmDialog.tsx
ccm_web/client/src/components/ErrorAlert.tsx
ccm_web/client/src/components/ExampleFileDownloadHeader.tsx
ccm_web/client/src/components/RowLevelErrorsContent.tsx
ccm_web/client/src/components/SuccessCard.tsx
ccm_web/client/src/components/ThirdPartyGradebookConfirmationTable.tsx
ccm_web/client/src/components/WarningAlert.tsx
ccm_web/client/src/models/FeatureUIData.tsx
ccm_web/client/src/models/canvas.ts
ccm_web/client/src/models/feature.ts
ccm_web/client/src/models/models.ts
ccm_web/client/src/pages/AddUMUsers.tsx
ccm_web/client/src/pages/BulkSectionCreate.tsx
ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
ccm_web/client/src/pages/GradebookCanvas.tsx
ccm_web/client/src/utils/FileParserWrapper.ts
ccm_web/client/src/utils/GradebookProcessor.tsx
ccm_web/client/src/utils/ThirdPartyGradebookProcessor.tsx
ccm_web/client/src/utils/fileUtils.ts
ccm_web/server/src/api/api.controller.ts
ccm_web/server/src/api/api.section.handler.ts
ccm_web/server/src/api/api.service.ts
ccm_web/server/src/canvas/canvas.interfaces.ts
ccm_web/server/src/canvas/canvas.scopes.ts

This PR implements the third-party gradebook formatting feature, which involved changes to the server and client. The main UI file is `client/src/pages/FormatThirdPartyGradebook.tsx`, but some filtering and validation logic was off-loaded to `client/src/utils/GradebookProcessor.tsx`.
In addition, while implementing the UI, I refactored `ErrorAlert` so that it uses a base `Alert` so I could create a `WarningAlert` and `ErrorAlert` could be used in `RowLevelErrorsContent`; I created a `ConfirmDialog` component that allows for file downloads; and I changed the `ExampleFileDownloadHeader` component to fit multiple use cases. Other miscellaneous changes are included.
**Note to reviewers**: you will need to add a new scope to your Canvas configuration (if you are enforcing scopes) for …

Implement Format Third-Party Gradebook feature (#21, #229)

---

ccm_web/client/src/App.tsx
ccm_web/client/src/models/FeatureUIData.tsx
ccm_web/client/src/models/feature.ts
ccm_web/client/src/pages/AddUMUsers.tsx
ccm_web/client/src/pages/BulkSectionCreate.tsx
ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
ccm_web/client/src/pages/GradebookCanvas.tsx
ccm_web/client/src/pages/MergeSections.tsx

This PR adds a missing help link to the "Format Third-Party Gradebook" feature and tweaks the language of both gradebook tools to be action-oriented. In addition, it made sense (at least to me) to tweak how title data is passed to each feature so it works the same as the `helpURLEnding` and `{feature}Props` don't have to be separately imported to each feature component.
The PR resolves #228 and #233.

Add help link to "Format Third-Party Gradebook", tweak gradebook tools' language (#228, #233)

---

ccm_web/client/src/components/InlineTextEdit.tsx
ccm_web/client/src/pages/Home.tsx

This PR refactors the `InlineTextEdit` component to provide a few improvements (see below), mainly the accessibility features suggested in issue #240. The PR aims to resolve issue #240 and maybe #151.
Improvements
- Pencil edit button is keyboard-accessible (changed underlying component to `Button`).
- Text field receives focus when the edit button is clicked.
- Text field has been made larger so edits are easier to see visually.
- The course name text is now an `h1` instead of a disabled text field when in not-editing mode. This also allows for display of long course names (which now wrap). It may also resolve other accessibility issues related to a missing `h1` on the home page.
- ARIA labels have been added to all involved buttons.
- When a request fails (because of a bad connection, …

Refactor `InlineTextEdit` and course name usage to improve usability/accessibility (#240)

---

ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx

Add check whether `getSectionsError` is `undefined` in "Format Third-Party Gradebook" (#249)

---

ccm_web/server/localTypes/express-session/index.d.ts
ccm_web/server/src/api/api.controller.ts
ccm_web/server/src/auth/auth.controller.ts
ccm_web/server/src/auth/session.guard.ts
ccm_web/server/src/canvas/canvas.controller.ts
ccm_web/server/src/lti/lti.service.ts
ccm_web/server/src/main.ts

This PR modifies application behavior around use of sessions in order to optimize security and provide better backend error reporting. The PR aims to resolve #171.
Task(s):
- Justification: Session should expire at some point. At the same or nearly the same time as the JWT cookie makes sense to me.
- Justification: This is needed as a consequence of the first task to have the backend server throw a better error if the session has expired. In practice, you may never see this, because the JWT cookie will expire before. However, if you manually remove the session cookie in your browser, or set the session cookie to expire earlier, you can get this to trigger, but only if it's a `GET` request. If it's something requiring a CSRF token, you will see a CSRF error since that global middlware …

Improve session (#171)

---

README.md

This PR makes small modifications to the "CCM Documentation" section so as to make the formatting more consistent with the rest of the document, fix a sample Docker command that gave the wrong file name, and make instructions clearer. The PR has no associated issue but is related to PR #224.

Modify layout, file name, and language in documentation section in `README.md`

---

ccm_web/client/src/components/BulkSectionCreateValidators.ts
ccm_web/client/src/components/InlineTextEdit.tsx
ccm_web/client/src/pages/BulkSectionCreate.tsx
ccm_web/client/src/pages/Home.tsx
ccm_web/client/src/utils/ThirdPartyGradebookProcessor.tsx
ccm_web/client/src/utils/canvasSectionNameValidator.ts
ccm_web/client/src/utils/validation.ts
ccm_web/package-lock.json
ccm_web/package.json

This PR tries to enhance and simplify validation in the front-end by leveraging the [`yup` library](https://github.com/jquense/yup#stringrequiredmessage-string--function-schema) to create schemas (encapsulating multiple tests and associated error messages) and use them to validate strings. The resulting `validation` module is used for field validation in `InlineTextEdit` and to replace identical basic string length validation in a couple other modules. The PR aims to resolve #244 and #276.
Note(s):
- This builds on -- but does not exactly reproduce work -- I did in ROHQ: https://github.com/tl-its-umich-edu/remote-office-hours-queue/blob/master/src/assets/src/validation.ts In ROHQ, I fired validation on each keystroke and reported remaining characters; in the interest of speed and …

Add `yup` for basic string validation, implement field validation in `InlineTextEdit` (#244, #276)

---

ccm_web/server/src/canvas/canvas.interfaces.ts
ccm_web/server/src/lti/lti.service.ts

issue-142 prevent user with wrong roles to access CCM tool

---

ccm_web/client/src/components/CSVFileName.tsx
ccm_web/client/src/components/ConfirmDialog.tsx
ccm_web/client/src/components/ErrorAlert.tsx
ccm_web/client/src/components/FileUpload.tsx
ccm_web/client/src/components/SuccessCard.tsx
ccm_web/client/src/components/WarningAlert.tsx
ccm_web/client/src/index.tsx
ccm_web/client/src/pages/GradebookCanvas.tsx
ccm_web/client/src/theme.ts
ccm_web/client/src/theme.tsx

Fixes #265, #75
1. This issue took a first pass at creating a theme and  getting all the generalized styling at one place. We could add more stuff to theme but this is a bare bone implementations
2. So far error, warn, success and info to users are coming from theme
This issue touches all of the features. Based on the Feedback i can add more here or later.

#265 #75 creating theme and fixing the error icon color

---

ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
ccm_web/client/src/pages/GradebookCanvas.tsx

This PR aims to resolve #271.
Resource(s):
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

Use `encodeURIComponent` with CSV download data for better character handling (#271)

---

ccm_web/client/src/components/CustomTable.tsx

Modify `CustomTable` so table semantics are used by screenreaders (#259)

---

ccm_web/client/src/components/CreateSelectSectionWidget.tsx
ccm_web/client/src/components/MultipleUserEnrollmentWorkflow.tsx
ccm_web/client/src/models/FeatureUIData.tsx
ccm_web/client/src/models/feature.ts
ccm_web/client/src/pages/AddNonUMUsers.tsx
ccm_web/client/src/pages/AddUMUsers.tsx
ccm_web/client/src/pages/Home.tsx
ccm_web/client/src/pages/MergeSections.tsx

This PR changes the `CreateSelectSectionWidget` component so that only admins (or equivalent) or teachers can see and use the section creation portion of the component.  The PR aims to resolve #284. @pushyamig also added changes to resolve #299.

Conditionally enable/disable section creation in `CreateSelectSectionWidget` (#284, #299)

---

ccm_web/client/src/components/ErrorAlert.tsx
ccm_web/client/src/components/MethodSelect.tsx
ccm_web/client/src/components/MultipleUserEnrollmentWorkflow.tsx
ccm_web/client/src/components/UserEnrollmentForm.tsx
ccm_web/client/src/models/FeatureUIData.tsx
ccm_web/client/src/pages/AddNonUMUsers.tsx
ccm_web/client/src/pages/AddUMUsers.tsx
ccm_web/client/src/pages/BulkSectionCreate.tsx
ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
ccm_web/client/src/pages/GradebookCanvas.tsx
ccm_web/client/src/pages/MergeSections.tsx

This PR adds any missing "Back" and "Start Again" buttons to features. In addition, 1) it makes some changes to the Add Non-UM Users feature so as to establish a common leaf component interface for `UserEnrollmentForm` and `MultipleUserEnrollmentWorkflow`, and 2) it ensures section data is reloaded whenever the user navigates to a section selection list, so accurate section and student number data are presented. The PR aims to resolve #238.

Add "Back" and "Start Again" buttons where relevant (#238)

---

ccm_web/client/src/components/CustomTable.tsx
ccm_web/client/src/pages/AddNonUMUsers.tsx

Per feedback received on #258 to use `aria-live` more granularly, this PR proposes two changes to `aria-live` usage in the application:
1) add `aria-live='polite'` as instructed to the container for the table pagination footer where the displayed rows are reported
2) remove `aria-live='polite'` that was added provisionally to the `AddNonUMUsers` container, as high-level usages like this are probably noisy and discouraged.
The PR seeks to resolve #258.

Add `aria-live` to `TablePagination`, remove it from `AddNonUMUsers` container (#258)

---

ccm_web/client/src/App.tsx
ccm_web/client/src/components/Breadcrumbs.tsx
ccm_web/client/src/components/InlineErrorAlert.tsx
ccm_web/client/src/index.tsx
ccm_web/client/src/pages/AccessDenied.tsx
ccm_web/client/src/pages/NotFound.tsx
ccm_web/client/src/utils/redirect.ts
ccm_web/package-lock.json
ccm_web/package.json
ccm_web/server/src/api/api.service.ts
ccm_web/server/src/app.module.ts
ccm_web/server/src/config.ts
ccm_web/server/src/lti/lti.service.ts
ccm_web/server/src/main.ts
config/.env.sample

The PR aims to resolve #48 and #209. This is somewhat experimental, but I believe it works well. I think it could help us handle some other issues, such as #253 and #312. It also is related to the closed issue #103.
Note(s):
- Switches from `app.useStaticAssets` to using `ServeStaticModule`, which is designed for single-page-applications.
- Because `ServeStaticModule` is now registered in `app.module.ts`, `helmet` and its Content Security Policy (CSP) settings now apply to the static assets served. This is likely a good thing, but means we need to do more CSP configuration (included here). Without them, the iframe was getting blocked in the Canvas test instance.
- Adds a higher-level instance of `Switch` in `client/index.tsx`, so we can have public routes for error messages and redirect …

Allow for client-side routing, set up `/access-denied` (#48, #209)

---

ccm_web/client/src/components/SectionSelectorWidget.tsx
ccm_web/client/src/pages/MergeSections.tsx

This PR aims to resolve #230 and #260.
Change(s):
1. Rather than relying on the provided `button` prop on `ListItem`, a `ButtonBase` was placed inside each `ListItem`. This follows the preferred approach identified by the accessibility team meant to resolve #260.
2.  Modified the `usePromise` hook for unmerging sections so an intermediate state variable (`sectionsToUnmerge`) and `useEffect` hook could be removed.
3. Made the text of the course name in a selected section blue, which I believe was the original intention, but wasn't happening before (reason...)
4. Used conditional rendering in a handful of instances (`props.multiSelect`, `props.search`, `props.header`), instead of using hidden styles (this resulted in some minor visual changes). I think this also had the side effect of …

Change list structure and otherwise improve `SectionSelectorWidget` (#230, #260)

---

ccm_web/client/src/models/canvas.ts
ccm_web/server/src/api/api.section.handler.ts
ccm_web/server/src/api/api.service.ts
ccm_web/server/src/api/dtos/api.section.users.dto.ts
ccm_web/server/src/canvas/canvas.interfaces.ts
ccm_web/server/src/canvas/canvas.scopes.ts
ccm_web/server/src/config.ts
config/.env.sample

Fixes #333 
1. Adding [test plan](https://docs.google.com/spreadsheets/d/1NxUnwo1cxD8gTxYK5DGwVwdb4u65u2FIp5iRcTpR7xg/edit#gid=0) testing this feature
2. Fixed a bug for Add Non-UM user Support consultant  no roles populated. Support consultant share same privileges in **CCM** as Account Admin role.
3. Add a check in the single Add UM user case for possible enrollments expected. Was already done with Multiple section user enroll case
4. For Non-UM users the code only displaying if the custom roles get picked up for Admin/Designer/Teacher and don't throw any validation error. Actual integration test can't be done until #247 get resolved
@ssciolla Thanks for the help with the validating the custom role props structure

I333 support librarian/assistant roles when enrolling users to sections

---

ccm_web/client/src/components/MultipleSectionEnrollmentWorkflow.tsx
ccm_web/client/src/components/MultipleUserEnrollmentWorkflow.tsx
ccm_web/client/src/components/SingleSectionEnrollmentWorkflow.tsx
ccm_web/package-lock.json
ccm_web/package.json
ccm_web/server/src/api/api.admin.handler.ts
ccm_web/server/src/api/api.course.handler.ts
ccm_web/server/src/api/api.section.handler.ts
ccm_web/server/src/api/api.service.ts
ccm_web/server/src/api/api.utils.ts
ccm_web/server/src/canvas/canvas.service.ts

The PR aims to resolve #326.
(I'm pretty sure this does the trick, and it kinda feels like magic 🪄 .)
Resource(s):
- https://github.com/sindresorhus/p-limit
- https://stackoverflow.com/a/52262024

Introduce `createLimitedPromises` wrapper for `p-limit` (#326)

---

ccm_web/client/src/components/MultipleSectionEnrollmentWorkflow.tsx

Add `tabIndex` to `TableRow` to allow keyboard accessibility of scrollable table (#349)

---

ccm_web/client/src/pages/FormatThirdPartyGradebook.tsx
ccm_web/client/src/pages/GradebookCanvas.tsx
ccm_web/client/src/utils/fileUtils.ts

Fixes #358 
This affects both Gradebook tools, not just 3rd-party gradebook

#358 file name change when downloading csv

---

ccm_web/server/src/health/health.controller.ts
ccm_web/server/src/health/health.module.ts

Fixes #343 
This issue is removing the redundant check against the APP URL since Nagios has there own way to check app up or down.
I have the PR on ccm-dev instance and Rick confirmed this change don't impact the Nagios configuration. 
I did not create an issue but tagging it to original issue with Health check

Removed the extra ping with App

---

ccm_web/server/src/config.ts
ccm_web/server/src/main.ts
ccm_web/server/test/app.e2e-spec.ts

This PR moves the core setting up of middleware and options (needed by both the main process and testing processes) into a separate function, which is then called in both `main.ts` and `app.e2e-spec.ts`. The PR aims to resolve #237.
Reminder of testing instructions:
1) Start up application using `docker compose up`
2) Enter running container: `docker exec -it ccm-web /bin/bash`
3) Run end-to-end test: `npm run test:e2e`

Extract core setup to provide basic fix to end-to-end test (#237)

---

ccm_web/server/src/lti/lti.service.ts

Consume course_id from canvas Id token as a string, then cast as a number for the globals API endpoint response

402: properly cast string course_id to number for global variable

---

docs/_includes/footer.html
docs/_layouts/default.html
docs/docker-compose-gh-pages.yml

Fixes #437
1. Upgrade to [Boostrap v5.3.3](https://getbootstrap.com/docs/5.3/getting-started/download/)
2. [year in the copyright at footer is dynamic now](https://shopify.github.io/liquid/filters/date/)
3. I am tagging jekyll docker image to run locally to v4.2.0 since latest version has some issue. [Until this issue](https://github.com/envygeeks/jekyll-docker/pull/347) is merged we cannot point to latest 
Latest changes from this branch are here if don't want to run locally: https://pushyamig.github.io/canvas-course-manager-next/gradebook-thirdparty.html
How to update CCM documentation: https://github.com/tl-its-umich-edu/canvas-course-manager-next/blob/main/README.md#ccm-documentation
**I am going to keep this issue as draft since a commit to main will lead to update in Prod**

#437 dynamic year for copyright and update latest bootstrap version

---

ccm_web/client/src/components/MultipleSectionEnrollmentWorkflow.tsx

Fixes #434 
I made this change thinking that cleaning up this loading screen was a requirement for another task. Seeing that it introduces a new design decision, I split it out into this PR.
Old loading backdrop
Proposed new loading backdrop

434: put loading spinner backdrop inside enrollment section accordion

---

ccm_web/client/src/components/SectionSelectorWidget.tsx

Fixes #427 
Fix section selection styling by refactoring ListItem button. ~~In trying to fix styling bugs on Merge Section page, I moved unmerge button to an alternate position.~~ Merge section styling is updated to retain old layout

427: fix section selection styling by refactoring ListItem Button

---

backend/settings.py
backend/urls.py
backend/views.py
config/.env.sample

This is used by the script for the onetrust banner that appears for analytics tracking. Adds PRIVACY_URL into environment variables and redirect the <URL>/privacy/ link to the U-M privacy policy resource.
Testing plan:
1. update env with the new PRIVACY_URL value
2. After starting your local instance, paste the ngrok or loophole URL into the browser and add /privacy/ to the end of it. 
3. submitting should redirect the page to the https://umich.edu/about/privacy/
If you'd like to do a more comprehensive test in an LTI in canvas, this response can be tested by using a VPN to target a EU country. This will result in the banner appearing, where you can select the "Privacy Policy" link and get directed to the page.

496: add privacy link for google analytics

---

backend/settings.py
backend/urls.py
config/.env.sample
requirements.txt

test plan: check to see if the monitoring endpoint is available using your local ngrok or loophole URL at <URL>/watchman/
The requested resource should be a report and response on the status of database, cache, etc.

fixes #485: add Watchman monitoring url
